In [16]:
import json
import csv
import pandas as pd
from transformers import AutoTokenizer, MarianMTModel

/Users/juandiego/Documents/proyects/learning-japanese/.venv/lib/python3.12/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [5]:
df = pd.read_csv('common_japanese_words.csv', encoding='utf-8')
df.head()

,#,week,day,japanese,pronounciation,translation,1d,2d,6d,12d,30d,100d,Last studied
0,1.0,1.0,1.0,行く,iku,go,TRUE,FALSE,FALSE,FALSE,FALSE,FALSE,NaN
1,2.0,1.0,1.0,見る,miru,"see, look at",TRUE,FALSE,FALSE,FALSE,FALSE,FALSE,NaN
2,3.0,1.0,1.0,多い,ooi,"a lot of, many",FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,NaN
3,4.0,1.0,1.0,家,ie,"home, household",FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,NaN
4,5.0,1.0,1.0,これ,kore,"this, this one",FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,NaN

In [11]:
subdf = df[['japanese', 'pronounciation', 'translation']]
subdf.head()

  japanese pronounciation      translation
0       行く            iku               go
1       見る           miru     see, look at
2       多い            ooi   a lot of, many
3        家             ie  home, household
4       これ           kore   this, this one

In [13]:
words = subdf.to_dict(orient='records')
print(f"Total: {len(words)}")

Total: 3000

In [15]:
with open('japaneseWords.json', 'w', encoding='utf-8') as f:
    json.dump(words, f, ensure_ascii=False, indent=2)

In [18]:
with open('japaneseWords.json', 'r', encoding='utf-8') as f:
    words = json.load(f)

print(f"Total: {len(words)}")

Total: 2998

In [17]:
model_name = f"Helsinki-NLP/opus-mt-en-es"
model = MarianMTModel.from_pretrained(model_name)
tokenizer = AutoTokenizer.from_pretrained(model_name)

Loading weights: 100%|██████████| 258/258 [00:00<00:00, 52266.73it/s]
/Users/juandiego/Documents/proyects/learning-japanese/.venv/lib/python3.12/site-packages/transformers/models/marian/tokenization_marian.py:176: UserWarning: Recommended: pip install sacremoses.
  warnings.warn("Recommended: pip install sacremoses.")

In [19]:
for word in words: 
    text = word["translation"]
    batch = tokenizer([text], return_tensors="pt")

    generated_ids = model.generate(**batch)
    translated_text = tokenizer.batch_decode(generated_ids, skip_special_tokens=True)[0]
    word["spanish"] = translated_text
    print(word)

    
with open('japaneseWords.json', 'w', encoding='utf-8') as f:
    json.dump(words, f, ensure_ascii=False, indent=2)

{'japanese': '行く', 'pronounciation': 'iku', 'translation': 'go', 'spanish': '¡Vamos!'}
{'japanese': '見る', 'pronounciation': 'miru', 'translation': 'see, look at', 'spanish': 'Mira, mira.'}
{'japanese': '多い', 'pronounciation': 'ooi', 'translation': 'a lot of, many', 'spanish': 'muchos, muchos'}
{'japanese': '家', 'pronounciation': 'ie', 'translation': 'home, household', 'spanish': 'hogar, hogar'}
{'japanese': 'これ', 'pronounciation': 'kore', 'translation': 'this, this one', 'spanish': 'Éste, éste.'}
{'japanese': 'それ', 'pronounciation': 'sore', 'translation': 'that, that one', 'spanish': 'que, que uno'}
{'japanese': '私', 'pronounciation': 'watashi', 'translation': 'I', 'spanish': 'I'}
{'japanese': '仕事', 'pronounciation': 'shigoto', 'translation': 'work, job', 'spanish': 'trabajo, trabajo'}
{'japanese': 'いつ', 'pronounciation': 'itsu', 'translation': 'when', 'spanish': 'cuando'}
{'japanese': 'する', 'pronounciation': 'suru', 'translation': 'do, make', 'spanish': 'hacer, hacer'}
{'japanese': '出る', 'pronounciation': 'deru', 'translation': 'go out, leave', 'spanish': 'Sal, vete.'}
{'japanese': '使う', 'pronounciation': 'tsukau', 'translation': 'use, make use of', 'spanish': 'uso, hacer uso de'}
{'japanese': '所', 'pronounciation': 'tokoro', 'translation': 'place', 'spanish': 'lugar'}
{'japanese': '作る', 'pronounciation': 'tsukuru', 'translation': 'make, create', 'spanish': 'make, create'}
{'japanese': '思う', 'pronounciation': 'omou', 'translation': 'think', 'spanish': 'Piensa'}
{'japanese': '持つ', 'pronounciation': 'motsu', 'translation': 'have, possess', 'spanish': 'tener, poseer'}
{'japanese': '買う', 'pronounciation': 'kau', 'translation': 'buy', 'spanish': 'comprar'}
{'japanese': '時間', 'pronounciation': 'jikan', 'translation': 'time, hour', 'spanish': 'tiempo, hora'}
{'japanese': '知る', 'pronounciation': 'shiru', 'translation': 'know', 'spanish': 'saber'}
{'japanese': '同じ', 'pronounciation': 'onaji', 'translation': 'same, identical', 'spanish': 'igual, idéntico'}
{'japanese': '今', 'pronounciation': 'ima', 'translation': 'now', 'spanish': 'ahora'}
{'japanese': '新しい', 'pronounciation': 'atarashii', 'translation': 'new', 'spanish': 'nuevo'}
{'japanese': 'なる', 'pronounciation': 'naru', 'translation': 'become', 'spanish': 'llegar a ser'}
{'japanese': 'まだ', 'pronounciation': 'mada', 'translation': '(not) yet, still', 'spanish': '(no) todavía, todavía'}
{'japanese': 'あと', 'pronounciation': 'ato', 'translation': 'after', 'spanish': 'después'}
{'japanese': '聞く', 'pronounciation': 'kiku', 'translation': 'hear, ask', 'spanish': 'Escucha, pregunta.'}
{'japanese': '言う', 'pronounciation': 'iu', 'translation': 'say, tell', 'spanish': 'di, di'}
{'japanese': '少ない', 'pronounciation': 'sukunai', 'translation': 'few, little', 'spanish': 'pocos, poco'}
{'japanese': '高い', 'pronounciation': 'takai', 'translation': 'high, tall', 'spanish': 'alto, alto'}
{'japanese': '子供', 'pronounciation': 'kodomo', 'translation': 'child', 'spanish': 'niño'}
{'japanese': 'そう', 'pronounciation': 'sou', 'translation': 'so, that way', 'spanish': 'Así que, de esa manera'}
{'japanese': 'もう', 'pronounciation': 'mou', 'translation': 'already, yet', 'spanish': 'ya, todavía'}
{'japanese': '学生', 'pronounciation': 'gakusei', 'translation': 'student', 'spanish': 'estudiante'}
{'japanese': '熱い', 'pronounciation': 'atsui', 'translation': 'hot (to touch)', 'spanish': 'caliente (tocar)'}
{'japanese': 'どうぞ', 'pronounciation': 'douzo', 'translation': 'please', 'spanish': 'Por favor.'}
{'japanese': '午後', 'pronounciation': 'gogo', 'translation': 'afternoon, p.m.', 'spanish': 'tarde, p.m.'}
{'japanese': '長い', 'pronounciation': 'nagai', 'translation': 'long', 'spanish': 'largo'}
{'japanese': '本', 'pronounciation': 'hon', 'translation': 'book, volume', 'spanish': 'libro, volumen'}
{'japanese': '今年', 'pronounciation': 'kotoshi', 'translation': 'this year (colloquial)', 'spanish': 'este año (coloquial)'}
{'japanese': 'よく', 'pronounciation': 'yoku', 'translation': 'often, well', 'spanish': 'a menudo, bueno'}
{'japanese': '彼女', 'pronounciation': 'kanojo', 'translation': 'she, one’s girlfriend', 'spanish': 'ella, la novia de uno'}
{'japanese': 'どう', 'pronounciation': 'dou', 'translation': 'how, what', 'spanish': '¿Cómo, qué?'}
{'japanese': '言葉', 'pronounciation': 'kotoba', 'translation': 'word, language', 'spanish': 'palabra, idioma'}
{'japanese': '顔', 'pronounciation': 'kao', 'translation': 'face', 'spanish': 'cara'}
{'japanese': '終わる', 'pronounciation': 'owaru', 'translation': 'finish, end', 'spanish': 'final, final'}
{'japanese': '一つ', 'pronounciation': 'hitotsu', 'translation': 'one (thing)', 'spanish': 'Uno (cosa)'}
{'japanese': 'あげる', 'pronounciation': 'ageru', 'translation': 'give, offer (colloquial)', 'spanish': 'dar, ofrecer (coloquial)'}
{'japanese': 'こう', 'pronounciation': 'kou', 'translation': 'like this, such', 'spanish': 'así, tal'}
{'japanese': '学校', 'pronounciation': 'gakkou', 'translation': 'school', 'spanish': 'escuela'}
{'japanese': 'くれる', 'pronounciation': 'kureru', 'translation': 'be given', 'spanish': 'se administrará'}
{'japanese': '始める', 'pronounciation': 'hajimeru', 'translation': 'start (something)', 'spanish': 'empezar (algo)'}
{'japanese': '起きる', 'pronounciation': 'okiru', 'translation': 'get up, get out of bed', 'spanish': 'Levántate, sal de la cama.'}
{'japanese': '春', 'pronounciation': 'haru', 'translation': 'spring', 'spanish': 'primavera'}
{'japanese': '午前', 'pronounciation': 'gozen', 'translation': 'morning, a.m.', 'spanish': 'Mañana, mañana.'}
{'japanese': '別', 'pronounciation': 'betsu', 'translation': 'another, different', 'spanish': 'otro, diferente'}
{'japanese': 'どこ', 'pronounciation': 'doko', 'translation': 'where', 'spanish': 'donde'}
{'japanese': '部屋', 'pronounciation': 'heya', 'translation': 'room', 'spanish': 'habitación'}
{'japanese': '若い', 'pronounciation': 'wakai', 'translation': 'young', 'spanish': 'jóvenes'}
{'japanese': '車', 'pronounciation': 'kuruma', 'translation': 'car, automobile', 'spanish': 'coche, automóvil'}
{'japanese': '置く', 'pronounciation': 'oku', 'translation': 'put, place', 'spanish': 'colocar, colocar'}
{'japanese': '住む', 'pronounciation': 'sumu', 'translation': 'live, reside', 'spanish': 'vivir, residir'}
{'japanese': '働く', 'pronounciation': 'hataraku', 'translation': 'work', 'spanish': 'trabajo'}
{'japanese': '難しい', 'pronounciation': 'muzukashii', 'translation': 'difficult', 'spanish': 'difícil'}
{'japanese': '先生', 'pronounciation': 'sensei', 'translation': 'teacher', 'spanish': 'profesor'}
{'japanese': '立つ', 'pronounciation': 'tatsu', 'translation': 'stand, rise', 'spanish': 'Levántate, levántate.'}
{'japanese': '呼ぶ', 'pronounciation': 'yobu', 'translation': 'call, name', 'spanish': 'llamada, nombre'}
{'japanese': '大学', 'pronounciation': 'daigaku', 'translation': 'university, college', 'spanish': 'universidad, universidad'}
{'japanese': '安い', 'pronounciation': 'yasui', 'translation': 'cheap, inexpensive', 'spanish': 'barato, barato'}
{'japanese': 'もっと', 'pronounciation': 'motto', 'translation': 'more', 'spanish': 'más'}
{'japanese': '帰る', 'pronounciation': 'kaeru', 'translation': 'go back home', 'spanish': 'Vuelve a casa.'}
{'japanese': '分かる', 'pronounciation': 'wakaru', 'translation': 'understand', 'spanish': 'entiéndelo.'}
{'japanese': '広い', 'pronounciation': 'hiroi', 'translation': 'wide, big', 'spanish': 'ancho, grande'}
{'japanese': '数', 'pronounciation': 'suu', 'translation': 'number', 'spanish': 'número'}
{'japanese': '近い', 'pronounciation': 'chikai', 'translation': 'near, close', 'spanish': 'cerca, cerca'}
{'japanese': 'そこ', 'pronounciation': 'soko', 'translation': 'there', 'spanish': 'allí.'}
{'japanese': '走る', 'pronounciation': 'hashiru', 'translation': 'run', 'spanish': 'ejecutar'}
{'japanese': '入れる', 'pronounciation': 'ireru', 'translation': 'put in', 'spanish': 'poner en'}
{'japanese': '教える', 'pronounciation': 'oshieru', 'translation': 'teach, tell', 'spanish': 'enseñar, decir'}
{'japanese': '歩く', 'pronounciation': 'aruku', 'translation': 'walk, go on foot', 'spanish': 'caminar, ir a pie'}
{'japanese': '会う', 'pronounciation': 'au', 'translation': 'meet', 'spanish': 'se reúne'}
{'japanese': '書く', 'pronounciation': 'kaku', 'translation': 'write', 'spanish': 'escribir'}
{'japanese': '頭', 'pronounciation': 'atama', 'translation': 'head', 'spanish': 'cabeza'}
{'japanese': '売る', 'pronounciation': 'uru', 'translation': 'sell', 'spanish': 'vender'}
{'japanese': '大好き', 'pronounciation': 'daisuki', 'translation': 'like (something) a lot', 'spanish': 'como (algo) mucho'}
{'japanese': '体', 'pronounciation': 'karada', 'translation': 'body, physique', 'spanish': 'cuerpo, físico'}
{'japanese': '直ぐ', 'pronounciation': 'sugu', 'translation': 'at once, soon', 'spanish': 'a la vez, pronto'}
{'japanese': '飛ぶ', 'pronounciation': 'tobu', 'translation': 'fly', 'spanish': 'volar'}
{'japanese': 'とても', 'pronounciation': 'totemo', 'translation': 'very (colloquial)', 'spanish': 'muy (coloquial)'}
{'japanese': '誰', 'pronounciation': 'dare', 'translation': 'who', 'spanish': 'quién'}
{'japanese': '好き', 'pronounciation': 'suki', 'translation': 'favorite, liked', 'spanish': 'favorito, me gusta'}
{'japanese': '読む', 'pronounciation': 'yomu', 'translation': 'read', 'spanish': 'debe decir'}
{'japanese': '次', 'pronounciation': 'tsugi', 'translation': 'next', 'spanish': 'siguiente'}
{'japanese': 'あなた', 'pronounciation': 'anata', 'translation': 'you', 'spanish': 'tú'}
{'japanese': '飲む', 'pronounciation': 'nomu', 'translation': 'drink', 'spanish': 'bebida'}
{'japanese': '古い', 'pronounciation': 'furui', 'translation': 'old', 'spanish': 'viejo'}
{'japanese': '質問', 'pronounciation': 'shitsumon', 'translation': 'question', 'spanish': 'pregunta'}
{'japanese': '今日', 'pronounciation': 'kyou', 'translation': 'today (colloquial)', 'spanish': 'hoy (coloquio)'}
{'japanese': '友達', 'pronounciation': 'tomodachi', 'translation': 'friend, companion (colloquial)', 'spanish': 'amigo, compañero (coloquial)'}
{'japanese': '早い', 'pronounciation': 'hayai', 'translation': 'early', 'spanish': 'Temprano'}
{'japanese': 'どれ', 'pronounciation': 'dore', 'translation': 'what, which', 'spanish': '¿Qué, qué?'}
{'japanese': '美しい', 'pronounciation': 'utsukushii', 'translation': 'beautiful', 'spanish': 'hermosa'}
{'japanese': 'いつも', 'pronounciation': 'itsumo', 'translation': 'always (colloquial)', 'spanish': 'siempre (coloquial)'}
{'japanese': '足', 'pronounciation': 'ashi', 'translation': 'leg, foot', 'spanish': 'pierna, pie'}
{'japanese': '起こす', 'pronounciation': 'okosu', 'translation': 'wake (someone) up', 'spanish': 'despierta (alguien) arriba'}
{'japanese': '見せる', 'pronounciation': 'miseru', 'translation': 'show', 'spanish': 'Mostrar'}
{'japanese': '娘', 'pronounciation': 'musume', 'translation': 'daughter, girl', 'spanish': 'hija, chica'}
{'japanese': '楽しむ', 'pronounciation': 'tanoshimu', 'translation': 'enjoy', 'spanish': 'disfrutar'}
{'japanese': '色', 'pronounciation': 'iro', 'translation': 'color', 'spanish': 'color'}
{'japanese': 'みんな', 'pronounciation': 'minna', 'translation': 'everybody (colloquial)', 'spanish': 'Todo el mundo (coloquial)'}
{'japanese': '取る', 'pronounciation': 'toru', 'translation': 'take, get', 'spanish': 'Toma, toma'}
{'japanese': '勉強', 'pronounciation': 'benkyou', 'translation': 'study', 'spanish': 'estudio'}
{'japanese': 'できる', 'pronounciation': 'dekiru', 'translation': 'can do, be good at', 'spanish': 'puede hacer, ser bueno en'}
{'japanese': '短い', 'pronounciation': 'mijikai', 'translation': 'short, brief', 'spanish': 'breve, breve'}
{'japanese': '落ちる', 'pronounciation': 'ochiru', 'translation': 'fall, come down', 'spanish': 'Cae, baja.'}
{'japanese': '息子', 'pronounciation': 'musuko', 'translation': 'son', 'spanish': 'hijo'}
{'japanese': '白い', 'pronounciation': 'shiroi', 'translation': 'white, blank', 'spanish': 'blanco, en blanco'}
{'japanese': '飛行機', 'pronounciation': 'hikouki', 'translation': 'airplane', 'spanish': 'avión'}
{'japanese': '病気', 'pronounciation': 'byouki', 'translation': 'illness', 'spanish': 'enfermedad'}
{'japanese': '冬', 'pronounciation': 'fuyu', 'translation': 'winter', 'spanish': 'invierno'}
{'japanese': '年', 'pronounciation': 'toshi', 'translation': 'year, age', 'spanish': 'año, edad'}
{'japanese': '重い', 'pronounciation': 'omoi', 'translation': 'heavy', 'spanish': 'pesado'}
{'japanese': '胸', 'pronounciation': 'mune', 'translation': 'chest, breast', 'spanish': 'pecho'}
{'japanese': '払う', 'pronounciation': 'harau', 'translation': 'pay (money, respect, attention, etc.)', 'spanish': 'paga (dinero, respeto, atención, etc.)'}
{'japanese': '軽い', 'pronounciation': 'karui', 'translation': 'light (of weight)', 'spanish': 'ligero (de peso)'}
{'japanese': '見つける', 'pronounciation': 'mitsukeru', 'translation': 'find', 'spanish': 'encontrar'}
{'japanese': '忘れる', 'pronounciation': 'wasureru', 'translation': 'forget, leave behind', 'spanish': 'Olvida, deja atrás'}
{'japanese': '酒', 'pronounciation': 'sake', 'translation': 'alcohol, rice wine', 'spanish': 'alcohol, vino de arroz'}
{'japanese': 'どちら', 'pronounciation': 'dochira', 'translation': 'which (polite)', 'spanish': 'que (polite)'}
{'japanese': '姉', 'pronounciation': 'ane', 'translation': '(one’s own) older sister', 'spanish': '(la propia) hermana mayor'}
{'japanese': '覚える', 'pronounciation': 'oboeru', 'translation': 'memorize, learn', 'spanish': 'memorizar, aprender'}
{'japanese': '狭い', 'pronounciation': 'semai', 'translation': 'narrow, small', 'spanish': 'estrecho, pequeño'}
{'japanese': '赤い', 'pronounciation': 'akai', 'translation': 'red', 'spanish': 'rojo'}
{'japanese': '着る', 'pronounciation': 'kiru', 'translation': 'wear, put on', 'spanish': 'Ponte, ponte.'}
{'japanese': '笑う', 'pronounciation': 'warau', 'translation': 'laugh, smile', 'spanish': 'Ríete, sonríe.'}
{'japanese': '一番', 'pronounciation': 'ichiban', 'translation': 'most, best', 'spanish': 'la mayoría, la mejor'}
{'japanese': '授業', 'pronounciation': 'jugyou', 'translation': 'class session, lecture', 'spanish': 'Sesión de clase, conferencia'}
{'japanese': '週', 'pronounciation': 'shuu', 'translation': 'week', 'spanish': 'semana'}
{'japanese': '漢字', 'pronounciation': 'kanji', 'translation': 'Chinese character', 'spanish': 'Carácter chino'}
{'japanese': '自転車', 'pronounciation': 'jitensha', 'translation': 'bicycle', 'spanish': 'bicicleta'}
{'japanese': '電車', 'pronounciation': 'densha', 'translation': 'train', 'spanish': 'tren'}
{'japanese': '探す', 'pronounciation': 'sagasu', 'translation': 'search for, look for', 'spanish': 'buscar, buscar'}
{'japanese': '紙', 'pronounciation': 'kami', 'translation': 'paper', 'spanish': 'papel'}
{'japanese': '歌う', 'pronounciation': 'utau', 'translation': 'sing', 'spanish': 'cantar'}
{'japanese': '遅い', 'pronounciation': 'osoi', 'translation': 'slow, late', 'spanish': 'lento, tarde'}
{'japanese': '首', 'pronounciation': 'kubi', 'translation': 'neck', 'spanish': 'cuello'}
{'japanese': '速い', 'pronounciation': 'hayai', 'translation': 'fast', 'spanish': 'rápido'}
{'japanese': '一緒に', 'pronounciation': 'issho ni', 'translation': 'together, at the same time', 'spanish': 'juntos, al mismo tiempo'}
{'japanese': '今月', 'pronounciation': 'kongetsu', 'translation': 'this month', 'spanish': 'este mes'}
{'japanese': '遊ぶ', 'pronounciation': 'asobu', 'translation': 'play', 'spanish': 'reproducir'}
{'japanese': '遠い', 'pronounciation': 'tooi', 'translation': 'far, distant', 'spanish': 'Lejos, distantes'}
{'japanese': '弱い', 'pronounciation': 'yowai', 'translation': 'weak', 'spanish': 'débil'}
{'japanese': '耳', 'pronounciation': 'mimi', 'translation': 'ear', 'spanish': 'oído'}
{'japanese': '座る', 'pronounciation': 'suwaru', 'translation': 'sit, sit down', 'spanish': 'Siéntate, siéntate.'}
{'japanese': '右', 'pronounciation': 'migi', 'translation': 'right', 'spanish': 'derecha'}
{'japanese': '浴びる', 'pronounciation': 'abiru', 'translation': 'take (a shower)', 'spanish': 'tomar (una ducha)'}
{'japanese': '肩', 'pronounciation': 'kata', 'translation': 'shoulder', 'spanish': 'hombro'}
{'japanese': '寝る', 'pronounciation': 'neru', 'translation': 'lie down and sleep, go to sleep', 'spanish': 'Acuéstate y duérmete, duérmete.'}
{'japanese': '消す', 'pronounciation': 'kesu', 'translation': 'switch off, turn off', 'spanish': 'Apaga, apaga.'}
{'japanese': '元気', 'pronounciation': 'genki', 'translation': 'healthy, energetic', 'spanish': 'sano, energético'}
{'japanese': '全部', 'pronounciation': 'zenbu', 'translation': 'all, whole', 'spanish': 'todo, todo'}
{'japanese': '去年', 'pronounciation': 'kyonen', 'translation': 'last year (colloquial)', 'spanish': 'el año pasado (coloquio)'}
{'japanese': '引く', 'pronounciation': 'hiku', 'translation': 'draw, pull', 'spanish': 'tire, tire'}
{'japanese': '図書館', 'pronounciation': 'toshokan', 'translation': 'library', 'spanish': 'biblioteca'}
{'japanese': '上げる', 'pronounciation': 'ageru', 'translation': 'raise, lift', 'spanish': 'Levantar, levantar'}
{'japanese': '緑', 'pronounciation': 'midori', 'translation': 'green', 'spanish': 'verde'}
{'japanese': '腕', 'pronounciation': 'ude', 'translation': 'arm', 'spanish': 'brazo'}
{'japanese': 'ドア', 'pronounciation': 'doa', 'translation': 'door (loan word)', 'spanish': 'puerta (préstamo palabra)'}
{'japanese': '女の子', 'pronounciation': 'onna no ko', 'translation': 'little girl', 'spanish': 'Niña'}
{'japanese': '男の子', 'pronounciation': 'otoko no ko', 'translation': 'boy', 'spanish': 'chico'}
{'japanese': '私たち', 'pronounciation': 'watashitachi', 'translation': 'we (colloquial)', 'spanish': 'nosotros (coloquial)'}
{'japanese': '近く', 'pronounciation': 'chikaku', 'translation': 'near, close to', 'spanish': 'cerca, cerca de'}
{'japanese': 'やる', 'pronounciation': 'yaru', 'translation': 'do, give', 'spanish': 'date, date'}
{'japanese': 'かなり', 'pronounciation': 'kanari', 'translation': 'fairly, rather', 'spanish': 'justo, más bien'}
{'japanese': '国', 'pronounciation': 'kuni', 'translation': 'country', 'spanish': 'país'}
{'japanese': '起こる', 'pronounciation': 'okoru', 'translation': 'happen', 'spanish': 'Acontecimientos'}
{'japanese': '秋', 'pronounciation': 'aki', 'translation': 'autumn, fall', 'spanish': 'otoño, otoño'}
{'japanese': '送る', 'pronounciation': 'okuru', 'translation': 'send', 'spanish': 'enviar'}
{'japanese': '死ぬ', 'pronounciation': 'shinu', 'translation': 'die', 'spanish': 'morir'}
{'japanese': '気持ち', 'pronounciation': 'kimochi', 'translation': 'feeling, sensation', 'spanish': 'sensación, sensación'}
{'japanese': '乗る', 'pronounciation': 'noru', 'translation': 'ride, take', 'spanish': 'cabalgar, tomar'}
{'japanese': 'いる', 'pronounciation': 'iru', 'translation': 'be present, stay', 'spanish': 'Estar presente, quedarse'}
{'japanese': '木', 'pronounciation': 'ki', 'translation': 'tree, wood', 'spanish': 'árbol, madera'}
{'japanese': '開ける', 'pronounciation': 'akeru', 'translation': 'open, unlock (doors, windows, etc.)', 'spanish': 'abrir, desbloquear (puertas, ventanas, etc.)'}
{'japanese': '閉める', 'pronounciation': 'shimeru', 'translation': 'shut, close (doors, windows, etc.)', 'spanish': 'cerrar, cerrar (puertas, ventanas, etc.)'}
{'japanese': '続く', 'pronounciation': 'tsuzuku', 'translation': 'continue, follow', 'spanish': 'continuar, seguir'}
{'japanese': 'お医者さん', 'pronounciation': 'oishasan', 'translation': 'doctor (polite)', 'spanish': 'médico (polita)'}
{'japanese': '円', 'pronounciation': 'en', 'translation': 'Japanese yen', 'spanish': 'Yen japonés'}
{'japanese': 'ここ', 'pronounciation': 'koko', 'translation': 'here', 'spanish': 'aquí'}
{'japanese': '待つ', 'pronounciation': 'matsu', 'translation': 'wait, wait for', 'spanish': 'Espera, espera.'}
{'japanese': '低い', 'pronounciation': 'hikui', 'translation': 'low, short', 'spanish': 'bajo, corto'}
{'japanese': 'もらう', 'pronounciation': 'morau', 'translation': 'receive', 'spanish': 'recibir'}
{'japanese': '食べる', 'pronounciation': 'taberu', 'translation': 'eat', 'spanish': 'comer'}
{'japanese': '兄', 'pronounciation': 'ani', 'translation': '(one’s own) older brother', 'spanish': '(el propio) hermano mayor'}